version: '3'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - api-credentials.env
      - mongo-variables.env
    environment:
      NODE_ENV: production
    depends_on:
      - mongodb
    restart: always

  caddy:
    build: 
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
    restart: always
  mongodb:
    image: mongo:4.4.4
    env_file:
      - mongo-variables.env
    expose:
      - 27017
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
