version: '3'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - api-credentials.env
      - mongo-variables.env
    environment:
      NODE_ENV: production
  caddy:
    build: 
      context: .
      dockerfile: Dockerfile.web
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
  mongodb:
    image: mongo:latest
    env_file:
      - mongo-variables.env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: