version: '3'

services:
  server:
    build: .
    environment:
      NODE_ENV: production
  caddy:
    image: caddy
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"

