version: '3'

services:
  server:
    build: ./server
    env_file:
      - api-credentials.env
      - mongo-variables.env
    volumes:
      - ./server/:/home/node/app
      - /home/node/app/node_modules
    image: "emotionmap-backend"
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      # HOKIDAR_USEPOLLING: 'true'
      
  client:
    build: ./client
    volumes:
      - ./client/:/home/node/app
      - /home/node/app/node_modules
    image: "emotionmap-client"
    depends_on:
      - server
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
  mongodb:
    image: mongo:latest
    env_file:
      - mongo-variables.env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: